# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170807_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deviceId', models.CharField(max_length=50)),
                ('simSerial', models.CharField(max_length=50)),
                ('msisdn', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userdetails',
            unique_together=set([('deviceId', 'simSerial', 'msisdn')]),
        ),
    ]
