# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170807_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=10)),
                ('generateTime', models.CharField(max_length=20)),
                ('UserDetailsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='TokenList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=50)),
                ('userDetailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastTimeUsed', models.CharField(max_length=50)),
                ('tokenListId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TokenList')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tokenlist',
            unique_together=set([('token',)]),
        ),
        migrations.AlterUniqueTogether(
            name='otplist',
            unique_together=set([('otp',)]),
        ),
    ]
