# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170807_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promotionText', models.CharField(max_length=50)),
                ('promoAmount', models.CharField(max_length=50)),
                ('promoTextSMS', models.CharField(max_length=10)),
                ('promoMb', models.CharField(max_length=10)),
            ],
        ),
    ]
