# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_promotiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeAmount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promotionText', models.CharField(max_length=150)),
                ('moneyAmount', models.IntegerField()),
                ('valid', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='PromotionDetails',
        ),
    ]
