# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_retailersoutletdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailersoutletdetails',
            name='shopServiceList',
            field=models.CharField(max_length=700),
        ),
    ]
