# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170820_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailersoutletdetails',
            name='shopServiceList',
        ),
    ]
