# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_retailersoutletdetails_shopservicelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailersoutletdetails',
            name='shopServiceList',
            field=models.CharField(default='', max_length=700),
        ),
    ]
