# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_retailersoutletdetails_shopservicelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailersoutletdetails',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='retailersoutletdetails',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
