# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170820_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailersoutletdetails',
            name='latitude',
            field=models.FloatField(),
        ),
    ]
